import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <div>Insta 2.0</div>

      </Head>
    </div>
  );
}
